from typing import TypedDict, List, Any

class GraphState(TypedDict):
    """
    Represents the state of our graph.
    
    Attributes:
        question: The user's original question
        generation: The final answer generated by the LLM
        documents: List of retrieved documents (optional)
    """
    question: str
    generation: str
    documents: List[Any]